dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven {
            url uri("https://api.mapbox.com/downloads/v2/releases/maven")
        }
        maven {
            url uri("https://nexus.link4.health/repository/link4health-anonymous/")
        }
        maven {
            url uri("https://maven.pkg.github.com/ihreapotheken/IA-SDK-Android")
            credentials {
                it.username = System.getenv("GITHUB_USERNAME") ?: "appsdk-service@4ofthem.eu"
                it.password = System.getenv("GITHUB_TOKEN") ?: "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"
            }
        }
        mavenLocal()
    }
}
